### ISSUE TITLE
Tests with a 'plan' and no assertions are skipped.

### ISSUE THREAD

**Issue by KoryNunn** [markwylde/basictap#3]
Reproduction:

```
test('x' => {
	t.plan(1);
})
```

**Comment by markwylde** [comment]
Ugh :( It looks like they're not skipped, but they just never finish, so the finish and finished never gets called.

**Comment by markwylde** [comment]
Fixed in a hacky way:
https://github.com/markwylde/basictap/blob/master/runner.js#L146

There must be a better way.
